version: '3.8'
services:
  jekyll:
    image: ruby:3.3
    container_name: chirpy_dev
    working_dir: /srv/jekyll
    command: >
      bash -lc "rm -rf vendor &&
      bundle config set --local path 'vendor/bundle' &&
      bundle install &&
      bundle exec jekyll serve --livereload --host 0.0.0.0 --port 4000 --incremental"
    ports:
      - "4000:4000"
    volumes:
      - ./:/srv/jekyll

